FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src/ ./src/
COPY .env ./.env

RUN npm run build

# ---- Runtime ----
FROM node:20-alpine AS runner

WORKDIR /app

COPY package*.json ./
COPY .env ./.env
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY public/ ./public/

EXPOSE 3000

CMD ["node", "dist/index.js"]